- name: Copy nextcloud compose files
  ansible.builtin.copy: 
    src: ../docker/nextcloud
    dest: ~{{ ansible_user }}
    owner: '{{ ansible_user }}'

- name: Run portainer compose
  community.docker.docker_compose:
    project_src: ~{{ ansible_user }}/nextcloud
    build: true
    files: 
      - docker-compose.yml