version: '3.8'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/hdd:/media/hdd
      - /mnt/ssd:/media/ssd
    networks:
     - nextcloud_network
    environments:
     - POSTGRES_HOST=nextcloud-db
     - POSTGRES_DB=nextcloud
     - POSTGRES_USER=nextcloud
     - POSTGRES_PASSWORD=nextcloud

  nextcloud-db:
    image: postgres:latest
    container_name: nextcloud-db
    restart: always
    networks:
     - nextcloud_network
    environments:
     - POSTGRES_DB=nextcloud
     - POSTGRES_USER=nextcloud
     - POSTGRES_PASSWORD=nextcloud
volumes:
  db:
  nextcloud:

networks:
  nextcloud_network:
  