version: '3.8'
services:
  portainer:
    container_name: portainer-app
    image: portainer/portainer-ce
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
       - portainer_network

volumes:
  portainer_data:

networks:
  portainer_network: