version: "3.8"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=falken.ua@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # labels:
    #   - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
    #   - "traefik.http.routers.http-catchall.entrypoints=web"
    #   - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
    #   - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.jarvis.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
      name: traefik