version: '3.8'
services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
     - ./client.json:/consul/config/client.json:ro
    command: "agent"

  registrator:
    image: gliderlabs/registrator:master
    container_name: registrator
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-ip cube.local -explicit -cleanup -resync 15 consul://jarvis.local:8500"
    depends_on:
      - consul

networks:
  default:
    name: consul