version: '3.8'
services:
  portainer:
    container_name: portainer-app
    image: portainer/portainer-ce
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
      - 9010:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
       - traefik
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.portainer.tls=true"
      # - "traefik.http.services.portainer.server.port=9443"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # - "traefik.http.services.portainer.loadbalancer.server.scheme=https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.jarvis.local`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.docker.network=traefik"

volumes:
  portainer_data:

networks:
  traefik:
    external: true