- name: Cube
  hosts: cube
  roles:
  - role: system
  - role: docker
  - role: containers/portainer/agent
    tags:
      - containers
  - role: containers/consul/agent
    tags:
      - containers
  - role: containers/nextcloud
    tags:
      - containers
  - name: Install samba
    role: docker/install
    container_name: samba
    compose_path: samba
    tags:
      - containers
      - samba