---
- name: Jarvis
  hosts: jarvis
  roles:
    - role: system
    - role: docker
    - role: containers/consul/server
      tags:
        - containers
    - role: containers/traefik
      tags:
        - containers
        - traefik
    - role: containers/portainer/server
      tags:
        - containers

    - role: containers/apps/aquila
      tags:
        - containers
        - aquila
    - name: Install samba
      role: docker/install
      container_name: samba
      compose_path: samba
      tags:
        - containers
        - samba
    - name: Install photoprism
      role: docker/install
      container_name: photoprism
      compose_path: photoprism
      tags:
        - containers
        - photoprism
