---
- name: Jarvis
  hosts: jarvis
  roles:
    - role: system
    - role: docker
    - role: containers/administration/portainer
      tags:
        - containers
    - role: containers/apps/aquila
      tags:
        - containers
...