---
- name: Jarvis
  hosts: jarvis
  roles:
    - role: system
    - role: docker
    - role: containers/portainer/server
      tags:
        - containers
    - role: containers/traefik
      tags:
        - containers
    - role: containers/consul/server
      tags:
        - containers
    - role: containers/apps/aquila
      tags:
        - containers
...