version: '3.8'
services:
  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: always
    user: 'www-data:1000'
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - nextcloud:/var/www/html
      - /mnt/ssd:/media/ssd
      - /mnt/hdd:/media/hdd
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: nextcloud-redis
      PHP_UPLOAD_LIMIT: 4G
      PHP_MEMORY_LIMIT: 5G
    networks:
      - consul
      - default

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always

  nextcloud-nginx:
    build: ./nginx
    container_name: nextcloud-nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - nextcloud
    environment:
      - SERVICE_NAME=nextcloud
      - SERVICE_TAGS=traefik.http.routers.nextcloud.rule=Host(`cloud.stepanov.page`),traefik.http.routers.nextcloud.entrypoints=websecure,traefik.http.routers.nextcloud.tls.certresolver=le,traefik.http.routers.nextcloud.tls=true,traefik.http.services.aquila-secure.loadbalancer.server.port=8080
    networks:
      - consul
      - default

  nextcloud-db:
    image: postgres:latest
    container_name: nextcloud-db
    restart: always
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  nextcloud-db:
  nextcloud:

networks:
  default:
    name: nextcloud
  consul:
    external: true
